apiVersion: v1
kind: Service
metadata:
  name: simple-node-service
  labels:
    run: simple-node
spec:
  selector:
    app: SimpleNode
    run: simple-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376

